name: aes_project
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy>=2.2
  - pandas>=2.3
  - scipy>=1.15
  - scikit-learn=1.6.1
  - xgboost=3.0.2
  - pytorch=2.5
  - torchvision=0.20
  - torchaudio=2.5
  - spacy=3.8
  - spacy-model-en_core_web_sm=3.8.0
  - streamlit=1.45
  - pip
  - pip:
      - transformers==4.52.4
      - tokenizers==0.21.1
      - huggingface-hub==0.32.4
      - hf-xet==1.1.3
      - textstat==0.7.7
      - gmpy2==2.2.1
      - altair>=5.5
      - pydeck>=0.9
      - gitpython==3.1.44
      - tqdm==4.67.1
      - rich==14.0.0
      - requests==2.32.3
      - dill==0.3.6
